### ISSUE TITLE
Dependencies issues - environment.yaml

### ISSUE THREAD

**Issue by FranckS** [RickGelhausen/HRIBO#55]
Hi,

Thanks for your work on what seems to be an amazing tool! I can't wait to try it out once I figure out some small dependencies issues for which I could use some help.

I'm walking through the documentation that you provided ( https://hribo.readthedocs.io/en/latest/source/overview.html#tools ), and I am having some issues related to python dependencies.
It seemed that HRIBO relies on DeepRibo (both for DataParser.py and for DeepRibo.py), which I've cloned via git (from https://github.com/Biobix/DeepRibo ).

The issue that I'm having is that it seems DeepRibo relies on some deprecated type aliases (in particular np.int) from numpy. I've searched and these aliases seem to have been deprecated from numpy 1.20.

I breifly thought about updating these (for instance replacing `np.int` by `np`), but I was scared of going through the rabbit hole of having to fix more and more things on DeepRibo.

So I thought I'd use numpy in version 1.19.5, but then my python (which is setup from the environment.yaml provided) wasn't compatible with it. I tried to force (in the environment.yml) python to an older version (like 3.7) but I got even more dependencies issues during the execution of the command `conda create --file HRIBO/environment.yaml`

By the way, it seems the webpage https://hribo.readthedocs.io/en/latest/source/overview.html#tools recommends using python 3.7, but the environment.yaml provided explicitly requests python=3.11.0=he550d4f_1_cpython
Can I please ask which one are you using personally?

I'm wondering if you are still having a runnable version of HRIBO, if you could please export and publish an updated version of your working environment. That would be a great help to avoid the dependency issues.

Just a final question/remark about "conda create" versus "conda env create": the same webpage also recommends to use:
`conda create --file HRIBO/environment.yaml`
But that fails with the error: conda create: error: one of the arguments -n/--name -p/--prefix is required
So of course I've tried:
`conda create --file HRIBO/environment.yaml -n hribo_env`
But that fails with the error: CondaValueError: could not parse 'name: hribo_env' in: HRIBO/environment.yaml
I've searched a bit, and it seems (according to https://github.com/conda/conda/issues/6827 but which is a fairly old thread) that "environment.yml doesn't work with conda install --file. You need to use conda env commands with environment.yml."
Therefore in everything I have attempted I have used:
`conda env create --file HRIBO/environment.yaml`
Is that what you would recommend to do as well?

Any help would be very much appreciated!
Kind regards.

**Comment by RickGelhausen** [comment]
Hi FrankS,

Thank you for your interest in HRIBO. 

I am currently working on improving the overall user-experience and cleanliness of the project, unfortunately this takes time as I have other important projects.

I recently fixed some dependency issues, but they seem to appear from time to time. 

Thank you for spotting the problems in the read-the-docs, I forgot to change some of the text on the last update. 

1. The recommendation for python3.7 is out-dated, I try to always test/update the workflow when a new snakemake version appears. 3.11 should work fine. 
2. ```conda create``` is also wrong. It should indeed by ```conda env create --file HRIBO/environment.yaml```

Getting `DeepRibo` to run is unfortunately quite tricky and it also took me a long time to get it working in `snakemake`. You actually do not need to manually install this at all, because I created a docker container for `DeepRibo` which is automatically downloaded by `snakemake` using `singularity`. 

In fact I usually use this call to run HRIBO, it specifies to using `singularity`.
```snakemake -p -k --use-conda --use-singularity --singularity-args " -c " --greediness 0 -s HRIBO/Snakefile --configfile HRIBO/config.yaml --directory ${PWD} -j 20 --latency-wait 60``` 


I have not used the workflow myself this month, I will run my test workflow and update eventual issues with dependencies and provide an according `environment.yaml` in a new minor-release. 

Depending on whether I encounter issues or not, this might take a up to a day.

Cheers,
Rick

**Comment by FranckS** [comment]
Hi @RickGelhausen 

Thanks so much for the supper fast response, I really appreciate it.
I'm doing to give a try to the command you mentioned yesterday that specifies the use of singularity for installing DeepRibo
`snakemake -p -k --use-conda --use-singularity --singularity-args " -c " --greediness 0 -s HRIBO/Snakefile --configfile HRIBO/config.yaml --directory ${PWD} -j 20 --latency-wait 60`
That will probably be better than what I did with my manual install of it. Thanks for the tips!

Thank you so much for being currently trying to fix other dependencies issues in which I will likely run into soon, that's very much appreciated. If you end up publishing a new environment.yaml or releasing a new version, I'll definitely try them out and help report issues encountered, in case that helps!

Kind regards,
Franck

**Comment by RickGelhausen** [comment]
Hi @FranckS,

I just released a new version 1.8.0, with my latest changes. All my tests run through. So it should run in a stable manner. 
Should you run into issue, please feel free to open another issue. 

I have not yet fully updated the documentation with the newest changes. But will do so soon. 

I also added a `run_hribo.sh` with the call to `snakemake` as the parameters become more and more. 

The `environment.yaml` is also updated to the newest version that I used for testing.

Kind regards,
Rick

**Comment by FranckS** [comment]
Hi @RickGelhausen

Thank you so much for having released a new version with the dependencies updated, and with a new script containing the snakemake command to use with all its parameters, that's truly amazing!

I'm going to test all that during the week-end and I will update (via a new ticket) if I encounter issues that I cannot solve.
Many many thanks again Rick, that's amazing work. Wishing you a great week-end!

Franck
